version: '3.5'

services:
  db:
    image: postgres:latest
    hostname: db
    restart: unless-stopped
    networks:
      - default
    environment:
      POSTGRES_DB: rinha
      POSTGRES_USER: rinha
      POSTGRES_PASSWORD: rinha
    ports:
      - '5432:5432'
    volumes:
      - ./config/database/schema.sql:/docker-entrypoint-initdb.d/init.sql
    command: postgres
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: '300MB'
