version: '3.5'

services:
  db:
    image: postgres:latest
    hostname: db
    restart: unless-stopped
    networks:
      - default
    environment:
      POSTGRES_DB: rinha
      POSTGRES_USER: rinha
      POSTGRES_PASSWORD: rinha
    ports:
      - '5432:5432'
    volumes:
      - ./config/database/schema.sql:/docker-entrypoint-initdb.d/init.sql
    command: |
      postgres -c max_connections=60
               -c shared_buffers=80MB
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: '315MB'

  api01: &api
    build:
      context: .
      dockerfile: Dockerfile
    hostname: api01
    restart: unless-stopped
    environment:
      - APP_PORT=3000
      - DB_HOST=db
      - DB_USER=rinha
      - DB_PASSWORD=rinha
      - DB_NAME=rinha
    depends_on:
      - db
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: '95MB'
    networks:
      - default
  api02:
    <<: *api
    hostname: api02
  nginx:
    image: nginx
    container_name: nginx
    volumes:
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - '9999:9999'
    depends_on:
      - api01
      - api02
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: '45MB'

networks:
  default:
    name: rinha-network
